### ISSUE TITLE
Not working for Ubunto 14.0.2

### ISSUE THREAD

**Issue by SyedAbubakar** [habedi/SystemC-AccessNoxim#1]
After following the whole procedure when i goes to make, al lot of problems occur. In short make is not happening. Some last lines are shown below.
./NoximMain.o:NoximMain.cpp:(.text._ZN8NoximNoCC1EN7sc_core14sc_module_nameE[NoximNoC::NoximNoC(sc_core::sc_module_name)]+0xcbbd): more undefined references to `VTT for sc_core::sc_signal<bool>' follow
./thermal_IF.o: In function`__static_initialization_and_destruction_0(int, int)':
thermal_IF.cpp:(.text+0x3d): undefined reference to `sc_core::sc_api_version_2_2_0::sc_api_version_2_2_0()'
./NoximVLink.o: In function`__static_initialization_and_destruction_0(int, int)':
NoximVLink.cpp:(.text+0xbd): undefined reference to `sc_core::sc_api_version_2_2_0::sc_api_version_2_2_0()'
./NoximLog.o: In function`__static_initialization_and_destruction_0(int, int)':
NoximLog.cpp:(.text+0x3d): undefined reference to `sc_core::sc_api_version_2_2_0::sc_api_version_2_2_0()'
collect2: error: ld returned 1 exit status

**Comment by habedi** [comment]
It's a typical compile time error(not related to your OS, that is Ubuntu 14), I think you need to tell the compiler(GCC) where to look for the right header files, have you done exactly as it's been described in my tutorial? please double check everything, especially this part:

``` shell
# Building AccessNoxim{do this inside AccessNoxim_v0.3}
export SYSTEMC_HOME=/usr/local/systemc231
export SYSTEMC_HEADERS=$SYSTEMC_HOME/include
export C_INCLUDE_PATH=$SYSTEMC_HEADERS
export CPLUS_INCLUDE_PATH=$SYSTEMC_HEADERS
cd bin
make
```

hope it solves your problem.

**Comment by SyedAbubakar** [comment]
I have followed the same procedure after that error came. What should i do now.

**Comment by habedi** [comment]
Sadly I don't have the time to resolve this issue right now, by as a short answer I guess something maybe is wrong with your compiler directives, mostly with the idea that your LINKING or INCLUDE path is wrong.

**Comment by SyedAbubakar** [comment]
Did it worked properly on Debian 8.0.0 with given systemc-3.2.1?

**Comment by habedi** [comment]
Sorry I didn't test it on Debian 8.
