### ISSUE TITLE
Installation Problem in Ubunto 14.0

### ISSUE THREAD

**Issue by Ayaz-Hussain** [habedi/SystemC-AccessNoxim#2]
Respected Sir i am getting problem in installation of the access noxim in ubunto 14.
Kindly help me to resolve this Error.The problem occurs in making access noxim. That gives errors related to:

"" ./NoximMain.o:NoximMain.cpp:(.text._ZN8NoximNoCC1EN7sc_core14sc_module_nameE[NoximNoC::NoximNoC(sc_core::sc_module_name)]+0xcbbd): more undefined references to VTT for sc_core::sc_signal<bool>' follow ./thermal_IF.o: In function__static_initialization_and_destruction_0(int, int)':
thermal_IF.cpp:(.text+0x3d): undefined reference to sc_core::sc_api_version_2_2_0::sc_api_version_2_2_0()' ./NoximVLink.o: In function__static_initialization_and_destruction_0(int, int)':
NoximVLink.cpp:(.text+0xbd): undefined reference to sc_core::sc_api_version_2_2_0::sc_api_version_2_2_0()' ./NoximLog.o: In function__static_initialization_and_destruction_0(int, int)':
NoximLog.cpp:(.text+0x3d): undefined reference to `sc_core::sc_api_version_2_2_0::sc_api_version_2_2_0()'
collect2: error: ld returned 1 exit status ""

**Comment by JackDing** [comment]
First of all, you should execute make -clean. Then make and the error will disappear.
